// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBd7rFio04_T_Ns7yVs0KBOMyFgJ5GvSw',
    appId: '1:335801509328:web:121f824777cde417b4c5d5',
    messagingSenderId: '335801509328',
    projectId: 'laptop-harbor-app-3bad6',
    authDomain: 'laptop-harbor-app-3bad6.firebaseapp.com',
    storageBucket: 'laptop-harbor-app-3bad6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-sGL2kpZVyxDP32MQbw9Fjf1XMHxl0b0',
    appId: '1:335801509328:android:c9519ab61e38d191b4c5d5',
    messagingSenderId: '335801509328',
    projectId: 'laptop-harbor-app-3bad6',
    storageBucket: 'laptop-harbor-app-3bad6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBd7rFio04_T_Ns7yVs0KBOMyFgJ5GvSw',
    appId: '1:335801509328:web:14d48b4f78f61b4bb4c5d5',
    messagingSenderId: '335801509328',
    projectId: 'laptop-harbor-app-3bad6',
    authDomain: 'laptop-harbor-app-3bad6.firebaseapp.com',
    storageBucket: 'laptop-harbor-app-3bad6.firebasestorage.app',
  );
}
